"""Validate and export the restaurant worksheet as an ES module."""

from collections import Counter
from pathlib import Path
import json

import openpyxl


WORKBOOK_NAME = "意大利瑞士行程_餐厅筛选清单.xlsx"
DAY_ORDER = ["9/4", "9/5", "9/6", "9/7", "9/8", "9/9", "9/10", "9/11", "9/12"]
REQUIRED_HEADERS = [
    "日期", "餐次/适用时段", "锚点类型", "对应景点/酒店", "序号", "推荐等级",
    "餐厅中文名", "餐厅英文/当地名", "Google Maps名称", "餐厅地址", "距离口径",
    "直线估算距离(km)", "预计到达时间", "是否顺路/说明", "爽口指数(5)", "为什么推荐",
    "推荐爽口菜", "菜单状态", "菜单链接", "餐厅链接", "Google Maps餐厅", "Google Maps导航",
    "8–12人预约等级", "预约/分桌说明", "人均餐标(当地币)", "币种", "汇率(CNY)",
    "人均餐标(RMB)", "价格说明", "餐厅坐标来源", "核验日期", "事实/推测标记",
]
URL_COLUMNS = ("菜单链接", "餐厅链接", "Google Maps餐厅", "Google Maps导航")
FIELD_MAP = {
    "rank": "序号", "level": "推荐等级", "nameCn": "餐厅中文名", "name": "餐厅英文/当地名",
    "address": "餐厅地址", "distanceKm": "直线估算距离(km)", "arrivalHint": "预计到达时间",
    "routeNote": "是否顺路/说明", "freshScore": "爽口指数(5)", "reason": "为什么推荐",
    "dishes": "推荐爽口菜", "menuStatus": "菜单状态", "menuUrl": "菜单链接", "siteUrl": "餐厅链接",
    "mapUrl": "Google Maps餐厅", "directionsUrl": "Google Maps导航", "booking": "8–12人预约等级",
    "bookingNote": "预约/分桌说明", "priceLocal": "人均餐标(当地币)", "currency": "币种",
    "rateCny": "汇率(CNY)", "priceCny": "人均餐标(RMB)", "priceNote": "价格说明",
    "verifiedAt": "核验日期", "factBoundary": "事实/推测标记",
}


def value(row, headers, header):
    result = row[headers[header]]
    return result


def main():
    root = Path(__file__).resolve().parents[1]
    workbook = root.parents[1] / WORKBOOK_NAME
    if not workbook.exists():
        raise FileNotFoundError(f"Workbook not found: {workbook}")
    sheet = openpyxl.load_workbook(workbook, data_only=True)["逐点餐厅清单"]
    actual_headers = [cell.value for cell in sheet[1]]
    missing = [header for header in REQUIRED_HEADERS if header not in actual_headers]
    if missing:
        raise ValueError(f"Missing headers: {missing}")
    headers = {header: actual_headers.index(header) for header in REQUIRED_HEADERS}

    rows = []
    for row_number, cells in enumerate(sheet.iter_rows(min_row=2, values_only=True), start=2):
        if all(cell is None or str(cell).strip() == "" for cell in cells):
            continue
        row = {field: value(cells, headers, source) for field, source in FIELD_MAP.items()}
        for source in URL_COLUMNS:
            if not str(value(cells, headers, source) or "").strip():
                raise ValueError(f"Blank URL field {source} at row {row_number}")
        rows.append((str(cells[headers["日期"]]), str(cells[headers["餐次/适用时段"]]),
                     str(cells[headers["锚点类型"]]), str(cells[headers["对应景点/酒店"]]), row))

    groups = {}
    for date, meal, anchor_type, anchor_name, restaurant in rows:
        groups.setdefault((date, meal, anchor_type, anchor_name), []).append(restaurant)
    bad_groups = {key: len(items) for key, items in groups.items() if len(items) != 3}
    if bad_groups:
        raise ValueError(f"Groups must contain exactly 3 restaurants: {bad_groups}")
    if len(groups) != 41 or len(rows) != 123:
        raise ValueError(f"Wrong final counts: {len(groups)} anchors and {len(rows)} restaurants")

    anchors = [{"date": date, "meal": meal, "anchorType": anchor_type, "anchorName": anchor_name,
                "restaurants": restaurants}
               for (date, meal, anchor_type, anchor_name), restaurants in groups.items()]
    output = root / "restaurants-data.mjs"
    serialized = json.dumps(anchors, ensure_ascii=False, indent=2)
    output.write_text(
        "// Generated by scripts/export_restaurants_data.py. Do not edit by hand.\n"
        f"export const DAY_ORDER = {json.dumps(DAY_ORDER, ensure_ascii=False)};\n\n"
        f"export const RESTAURANT_DATA = {serialized};\n\n"
        "export function anchorsForDay(day) {\n"
        "  const sharedHomestayDays = ['9/9', '9/10', '9/11'];\n"
        "  return RESTAURANT_DATA.filter(anchor => anchor.date === day || (sharedHomestayDays.includes(day) && anchor.date === '9/9–9/11'));\n"
        "}\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
